[project]
name = "statpp"
version = "0.1.0"
description = "Empirical performance ratings for osu!"
readme = "README.md"
requires-python = "==3.12.9"
dependencies = [
    "aiolimiter>=1.2.1",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "numpy>=2.5.1",
    "pony>=0.7.19",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "rosu-pp-py>=4.0.2",
]
