[project]
name = "statpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "numpy>=2.4.4",
    "osupyparser>=1.0.7",
    "pandas>=3.0.2",
    "pip>=26.0.1",
    "polars>=1.40.1",
    "pyarrow>=24.0.0",
    "rosu-pp-py>=4.0.2",
    "torch>=2.11.0",
    "tqdm>=4.67.3",
]
