//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "beatmapmod_vector")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub beatmapmod_id: i32,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub vec: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::beatmapmod::Entity",
        from = "Column::BeatmapmodId",
        to = "super::beatmapmod::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Beatmapmod,
}

impl Related<super::beatmapmod::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Beatmapmod.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
