//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "beatmapmod")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "unq_beatmapmod__beatmap_mod")]
    pub beatmap: i32,
    #[sea_orm(unique_key = "unq_beatmapmod__beatmap_mod")]
    pub r#mod: String,
    #[sea_orm(column_type = "Double")]
    pub difficulty: f64,
    #[sea_orm(column_type = "Double")]
    pub success_rate: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::beatmap::Entity",
        from = "Column::Beatmap",
        to = "super::beatmap::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Beatmap,
    #[sea_orm(has_one = "super::beatmapmod_vector::Entity")]
    BeatmapmodVector,
}

impl Related<super::beatmap::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Beatmap.def()
    }
}

impl Related<super::beatmapmod_vector::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BeatmapmodVector.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
