//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "beatmap")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub title: String,
    pub artist: String,
    pub diffname: String,
    #[sea_orm(column_type = "Double")]
    pub osu_difficulty: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::beatmapmod::Entity")]
    Beatmapmod,
}

impl Related<super::beatmapmod::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Beatmapmod.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
