//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(unique)]
    pub osu_id: i32,
    pub username: String,
    #[sea_orm(column_type = "Double")]
    pub total_pp: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::user_vector::Entity")]
    UserVector,
}

impl Related<super::user_vector::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserVector.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
